= Demo-Dokumentation
Vorname Nachname <vorname.nachname@htw-dresden.de>
include::attributes.inc.adoc[]

Praktikumsbeispiel für die Verwendung von Diagrammen mit PlantUML in Asciidoctor.


== PlantUML-Diagramme

Diagramme mit der PlantUML-Notation können im Asciidoctor-Dokument direkt als Block *eingebettet* oder als externe Datei *inkludiert* werden.

=== Funktionstest

Ein Testdiagramm, ob die Vorschau in VS Code bzw. die Generierung mit Asciidoctor funktioniert.

.Testdiagramm
[plantuml, "{diagramsdir}/hello_world", svg]
....
actor Human
(\nWorld\n) #dff
note right of Human : Hello
....

.Graphiz Dot Test
[plantuml, "{diagramsdir}/testdot", svg]
....
@startuml
testdot
@enduml
....

Hinweise zur Einrichtung siehe zugehörige Aufgabenstellung.

=== Eingebettet

Ein Beispiel für ein direkt im Dokument eingebettetes PlantUML-Diagramm.

.Klassendiagramm mit PlantUML 
[plantuml, "{diagramsdir}/syntax-example1", svg]  
....
class Graphic 
interface Shape <<Interface>> {
  draw()
}
class Circle
class Triangle
class Square

Graphic -> Shape
Shape <|.. Circle
Shape <|.. Triangle
Shape <|.. Square
....

=== Inkludiert

Ein Beispiel für ein im Dokument inkludiertes PlantUML-Diagramm als externe Datei.

.Klassendiagramm mit PlantUML
[plantuml, "{diagramsdir}/syntax-example2", svg]
....
include::{plantumlsdir}/syntax-example2.puml[]
....

.Usecasediagram mit PlantUML
[plantuml, "{diagramsdir}/example-usecase-diagram", svg]
....
include::{plantumlsdir}/example-usecase-diagram.puml[]
....

.Klassendiagram mit PlantUML
[plantuml, "{diagramsdir}/example-class-diagram", svg]
....
include::{plantumlsdir}/example-class-diagram.puml[]
....

.Aktivitätendiagram mit PlantUML
[plantuml, "{diagramsdir}/example-activity-diagram", svg]
....
include::{plantumlsdir}/example-activity-diagram.puml[]
....

.C4-Modelldiagram mit PlantUML
[plantuml, "{diagramsdir}/example-c4-modell-diagram", svg]
....
include::{plantumlsdir}/example-c4-modell-diagram.puml[]
....
